name: copper_server
description: WebSocket сервер для мессенджера
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0